// nextjs/src/components/AuthCard.tsx
"use client";

import type { FormEventHandler, ReactNode } from "react";

type AuthCardProps = {
  title: string;
  onSubmit: FormEventHandler<HTMLFormElement>;
  children: ReactNode;
  footer?: ReactNode;
  isSubmitting?: boolean;
};

const AuthCard = ({ title, onSubmit, children, footer, isSubmitting }: AuthCardProps) => (
  <main className="page">
    <div className="card">
      <h1>{title}</h1>
      <form className="stack" onSubmit={onSubmit}>
        {children}
        <button type="submit" className="primary" disabled={isSubmitting}>
          {isSubmitting ? "Please wait..." : title}
        </button>
      </form>
      {footer}
    </div>
  </main>
);

export default AuthCard;

// vue/src/components/AuthCard.vue
<template>
  <main class="page">
    <div class="card">
      <h1>{{ title }}</h1>
      <form class="stack" @submit.prevent="onSubmit">
        <slot />
        <button class="primary" type="submit" :disabled="isSubmitting">
          <slot name="cta">{{ isSubmitting ? 'Please wait...' : title }}</slot>
        </button>
      </form>
      <slot name="footer" />
    </div>
  </main>
</template>

<script setup lang="ts">
interface Props {
  title: string;
  isSubmitting?: boolean;
  onSubmit: () => void | Promise<void>;
}

const props = defineProps<Props>();
const emit = defineEmits<{ submit: [] }>();

const onSubmit = async () => {
  emit("submit");
  await props.onSubmit?.();
};
</script>
